name: Testing fastapi_aws_test

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:

      fastapi_aws_test-db:
        image: bitnami/mysql:8.0.28
        env:
          MYSQL_PASSWORD: fastapi_aws_test
          MYSQL_USER: fastapi_aws_test
          MYSQL_DATABASE: fastapi_aws_test
          ALLOW_EMPTY_PASSWORD: yes
        options: >-
          --health-cmd="mysqladmin ping -u root"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Verify MySQL connection
      run: |
        while ! mysqladmin ping -h"localhost" -P"3306" --silent; do
          sleep 1
        done
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="fastapi_aws_test" .
      env:
        FASTAPI_AWS_TEST_HOST: "0.0.0.0"
        FASTAPI_AWS_TEST_DB_HOST: localhost
